### ISSUE TITLE
Keep a revision history

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-configurator#1]
Sometimes, invalid configuration can prevent user servers from starting. Usually, these can be fixed by reverting the invalid configuration. When 2i2c engineers do this via github, we can revert the PR to revert the econfig.  With the configurator, this means the hub admin has to write them down manually first - there's no way to 'revert' a change.

We should provide simple, wiki-style, linear version history for config changes. Admins can then revert hub config when things go wrong. A linear history is more than good enough - GUI history UX is hard when using a DAG (like git).Besides, any complex big config change needing branches should be done via git.

### TODO

- [ ] Add concept of versions to storage backend. Should be pluggable.
- [ ] Add version control to current filesystem based provider, using predictable naming and symlinks.
- [ ] Build backend support for listing revisions, and viewing them. No edits or deletes - this will be an append-only version history.
- [ ] Build UX and backend support for creating a new version. 
- [ ] Build UX to 'revert' to a previous version of the config. This will just get the old config and create a new version with it.
