### ISSUE TITLE
Support kubespawner profiles

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-configurator#4]
kubespawner's profiles let users pick from one of many *profiles*, offering different options like memory, image, etc. When the user makes a selection, a set of traitlets matching profile is set on kubespawner, and then launched. By allowing hub admins to configure these directly, we can drastically reduce the number of things hub admins need 2i2c staff for.

Configurator already overrides traitlets on the spawner object, so we need to tweak our UI and data model to build the configurator around the idea of profiles. If there is only one profile, it is the default and no profile selection screen is shown. 

### TODO

- [ ] Change the datamodel in the backend to be oriented around profiles, where each profile matches the schema provided to the configurator
- [ ] Add profile support to our spawner mixin
- [ ] Change the front-end data model to allow multiple set of configurations, each being a 'profile'. 
- [ ] Bzuid UX for 'CRUD' operations on the profiles
