### ISSUE TITLE
Show progress when saving config

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/jupyterhub-configurator#5]
Our [first 'user test'](https://github.com/2i2c-org/pilot-hubs/pull/329#issuecomment-809747595) left us with a lot of very useful comments (thanks @zaneselvans!). A primary theme here is that we don't actually display any progress when you save your config. No state changes, no spinners, etc. Very confusing!

### TODO

- [ ] Make it clearer that you need to hit the 'submit' button to save your changes
- [ ] Show indication of saved state - 'needs saving', 'saving', 'saved!'
- [ ] If save fails, provide a decent error message
